# Generated by Django 5.0.2 on 2026-02-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='available_quantity',
            new_name='stock_quantity',
        ),
        migrations.AddField(
            model_name='clothing',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Party', 'Party'), ('Formal', 'Formal'), ('Casual', 'Casual')], default='Casual', max_length=50),
        ),
        migrations.AddField(
            model_name='clothing',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('Formal Wear', 'Formal Wear'), ('Casual', 'Casual'), ('Party Wear', 'Party Wear'), ('Traditional', 'Traditional'), ('Sports Wear', 'Sports Wear')], max_length=50),
        ),
    ]
