# Generated by Django 5.0.2 on 2026-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_available_quantity_clothing_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.CharField(help_text='Comma-separated sizes like S, M, L', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_clothing_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=255, null=True),
        ),
    ]
