# Generated by Django 5.0.2 on 2026-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_clothing_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
