# Generated by Django 5.0.2 on 2026-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clothing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closing_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='opening_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
