# Generated by Django 5.0.2 on 2026-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_closing_time_user_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='user',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
