# Generated by Django 5.0.2 on 2026-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_closing_time_remove_user_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recommendations_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
