# Generated by Django 5.0.2 on 2026-03-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_location_sharing_user_profile_visibility_and_more'),
        ('donations', '0002_alter_donation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_clothing', to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20),
        ),
    ]
