# Generated by Django 5.0.2 on 2026-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_clothing_donation_alter_clothing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_status',
        ),
        migrations.AddField(
            model_name='clothing',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
    ]
