# Generated by Django 5.0.2 on 2026-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/business_card/'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/citizenship/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
