# Generated by Django 5.0.2 on 2026-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('donation', 'Donation'), ('system', 'System'), ('chat', 'Chat'), ('reminder', 'Reminder'), ('overdue', 'Overdue')], default='system', max_length=20),
        ),
    ]
