# Generated by Django 5.0.2 on 2026-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
