# Generated by Django 5.0.2 on 2026-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rental_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rented', 'Rented'), ('returned_pending', 'Returned Pending'), ('returned_confirmed', 'Returned Confirmed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
