# Generated by Django 5.0.2 on 2026-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
