# Generated by Django 5.0.2 on 2026-01-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Skirt', 'Skirt'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex'), ('Other', 'Other')], max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Used', 'Used')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('donation_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Collected', 'Collected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(limit_choices_to={'role': 'Store'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
