# Generated by Django 5.0.2 on 2026-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
