# Generated by Django 5.0.2 on 2026-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('jacket', 'Jacket'), ('traditional', 'Traditional Wear'), ('other', 'Other')], max_length=50),
        ),
    ]
